input 
{ 
 file {
 path => ["/home/student/elastic-stack/kibana/data/logs"]
 start_position => "beginning"
 sincedb_path => "/dev/null"
 }
}

filter 
{
 grok {
 match => {
 "message" => "%{COMBINEDAPACHELOG}"
 }
 }
 mutate {
 convert => { "bytes" => "integer" }
 }
 date {
 match => [ "timestamp", "dd/MMM/YYYY:HH:mm:ss Z" ]
 locale => en
 remove_field => "timestamp"
 }
 geoip {
 source => "clientip"
 }
 useragent {
 source => "agent"
 target => "useragent"
 }
}

output 
{ 
 stdout { 
 codec => dots
 } 
 elasticsearch {
 hosts => ["localhost:9200"],
    data_stream => true
    data_stream_type => "logs"
    data_stream_dataset => "test"
    data_stream_namespace => "kibana"
 }
}
